# Generated by Django 4.1.1 on 2022-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward", models.IntegerField()),
                ("statement", models.CharField(max_length=255)),
                ("tags", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
